### ISSUE TITLE
Key lenght should be "crypto_box_SECRETKEYBYTES" on NaclBox.keyPair(fromSecretKey: Data)

### ISSUE THREAD

**Issue by LucaCardelli** [bitmark-inc/tweetnacl-swiftwrap#1]
https://github.com/bitmark-inc/tweetnacl-swiftwrap/blob/f00bfede27745d992105c20db614283120bb03a5/Sources/TweetNacl/TweetNacl.swift#L301

this line should be:
`if sk.count != crypto_box_SECRETKEYBYTES {`

**Comment by emimeswift** [comment]
Any chance the issue above could be fixed?

**Comment by coreagile** [comment]
Is this project still maintained? This is a critical defect for those of us who need deterministic key generation.

**Comment by anhnguyenbitmark** [comment]
Thanks for pointing that out. We will review and fix it soon.

**Comment by anhnguyenbitmark** [comment]
It has been fixed in PR https://github.com/bitmark-inc/tweetnacl-swiftwrap/pull/2
