### ISSUE TITLE
Make a 1.1.0 release

### ISSUE THREAD

**Issue by danielrbrowne** [bitmark-inc/tweetnacl-swiftwrap#10]
The [recent changes since the current 1.0.2 release](https://github.com/bitmark-inc/tweetnacl-swiftwrap/compare/1.0.2...HEAD) should be made available as a 1.1.0 release (based on the public API additions).

**Comment by MeenaAlfons** [comment]
@anhnguyenbitmark Could you please create a release for these recent changes? Thank you 🙏 

This is troubling because the users of `pusher/pusher-http-swift` cannot depend on its versions because `pusher/pusher-http-swift` currently depends on a "revision" of `bitmark-inc/tweetnacl-swiftwrap`

**Comment by anhnguyenbitmark** [comment]
Sure! Let me do it.
